// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Freya.Types.Uri.Template.Provider.DesignTime")>]
[<assembly: AssemblyProductAttribute("Freya.Types.Uri.Template.Provider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Freya.Types.Uri.Template.Provider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Freya.Types.Uri.Template.Provider.DesignTime"
    let [<Literal>] AssemblyProduct = "Freya.Types.Uri.Template.Provider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Freya.Types.Uri.Template.Provider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
